//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingSpawnPoints {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildingSpawnPoints.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add point.
        /// </summary>
        internal static string Panel_AddPoint {
            get {
                return ResourceManager.GetString("Panel_AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add vehicle type.
        /// </summary>
        internal static string Panel_AddVehicle {
            get {
                return ResourceManager.GetString("Panel_AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add vehicle type group.
        /// </summary>
        internal static string Panel_AddVehicleGroup {
            get {
                return ResourceManager.GetString("Panel_AddVehicleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}°.
        /// </summary>
        internal static string Panel_AngleFormat {
            get {
                return ResourceManager.GetString("Panel_AngleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}m.
        /// </summary>
        internal static string Panel_PositionFormat {
            get {
                return ResourceManager.GetString("Panel_PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building #{0}.
        /// </summary>
        internal static string Panel_Title {
            get {
                return ResourceManager.GetString("Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spawn.
        /// </summary>
        internal static string PointType_Spawn {
            get {
                return ResourceManager.GetString("PointType_Spawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspawn.
        /// </summary>
        internal static string PointType_Unspawn {
            get {
                return ResourceManager.GetString("PointType_Unspawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Property_PointType {
            get {
                return ResourceManager.GetString("Property_PointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        internal static string Property_Position {
            get {
                return ResourceManager.GetString("Property_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate tool.
        /// </summary>
        internal static string Settings_ShortcutActivateTool {
            get {
                return ResourceManager.GetString("Settings_ShortcutActivateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building #{0}.
        /// </summary>
        internal static string Tool_InfoHoverBuilding {
            get {
                return ResourceManager.GetString("Tool_InfoHoverBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select building.
        /// </summary>
        internal static string Tool_InfoSelectBuilding {
            get {
                return ResourceManager.GetString("Tool_InfoSelectBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string VehicleType_All {
            get {
                return ResourceManager.GetString("VehicleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambulance.
        /// </summary>
        internal static string VehicleType_Ambulance {
            get {
                return ResourceManager.GetString("VehicleType_Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambulance copter.
        /// </summary>
        internal static string VehicleType_AmbulanceCopter {
            get {
                return ResourceManager.GetString("VehicleType_AmbulanceCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balloon.
        /// </summary>
        internal static string VehicleType_Balloon {
            get {
                return ResourceManager.GetString("VehicleType_Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bicycle.
        /// </summary>
        internal static string VehicleType_Bicycle {
            get {
                return ResourceManager.GetString("VehicleType_Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bus.
        /// </summary>
        internal static string VehicleType_Bus {
            get {
                return ResourceManager.GetString("VehicleType_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cable car.
        /// </summary>
        internal static string VehicleType_CableCar {
            get {
                return ResourceManager.GetString("VehicleType_CableCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo plane.
        /// </summary>
        internal static string VehicleType_CargoPlane {
            get {
                return ResourceManager.GetString("VehicleType_CargoPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo ship.
        /// </summary>
        internal static string VehicleType_CargoShip {
            get {
                return ResourceManager.GetString("VehicleType_CargoShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo train.
        /// </summary>
        internal static string VehicleType_CargoTrain {
            get {
                return ResourceManager.GetString("VehicleType_CargoTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo truck.
        /// </summary>
        internal static string VehicleType_CargoTruck {
            get {
                return ResourceManager.GetString("VehicleType_CargoTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disaster.
        /// </summary>
        internal static string VehicleType_Disaster {
            get {
                return ResourceManager.GetString("VehicleType_Disaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disaster copter.
        /// </summary>
        internal static string VehicleType_DisasterCopter {
            get {
                return ResourceManager.GetString("VehicleType_DisasterCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fire copter.
        /// </summary>
        internal static string VehicleType_FireCopter {
            get {
                return ResourceManager.GetString("VehicleType_FireCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fire truck.
        /// </summary>
        internal static string VehicleType_FireTruck {
            get {
                return ResourceManager.GetString("VehicleType_FireTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fishing boat.
        /// </summary>
        internal static string VehicleType_FishingBoat {
            get {
                return ResourceManager.GetString("VehicleType_FishingBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Garbage truck.
        /// </summary>
        internal static string VehicleType_GarbageTruck {
            get {
                return ResourceManager.GetString("VehicleType_GarbageTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hearse.
        /// </summary>
        internal static string VehicleType_Hearse {
            get {
                return ResourceManager.GetString("VehicleType_Hearse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maintenance truck.
        /// </summary>
        internal static string VehicleType_MaintenanceTruck {
            get {
                return ResourceManager.GetString("VehicleType_MaintenanceTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metro train.
        /// </summary>
        internal static string VehicleType_MetroTrain {
            get {
                return ResourceManager.GetString("VehicleType_MetroTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monorail.
        /// </summary>
        internal static string VehicleType_Monorail {
            get {
                return ResourceManager.GetString("VehicleType_Monorail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Park maintenance.
        /// </summary>
        internal static string VehicleType_Park {
            get {
                return ResourceManager.GetString("VehicleType_Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger blimp.
        /// </summary>
        internal static string VehicleType_PassengerBlimp {
            get {
                return ResourceManager.GetString("VehicleType_PassengerBlimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger copter.
        /// </summary>
        internal static string VehicleType_PassengerCopter {
            get {
                return ResourceManager.GetString("VehicleType_PassengerCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger ferry.
        /// </summary>
        internal static string VehicleType_PassengerFerry {
            get {
                return ResourceManager.GetString("VehicleType_PassengerFerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger plane.
        /// </summary>
        internal static string VehicleType_PassengerPlane {
            get {
                return ResourceManager.GetString("VehicleType_PassengerPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger ship.
        /// </summary>
        internal static string VehicleType_PassengerShip {
            get {
                return ResourceManager.GetString("VehicleType_PassengerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger train.
        /// </summary>
        internal static string VehicleType_PassengerTrain {
            get {
                return ResourceManager.GetString("VehicleType_PassengerTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Police.
        /// </summary>
        internal static string VehicleType_Police {
            get {
                return ResourceManager.GetString("VehicleType_Police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Police copter.
        /// </summary>
        internal static string VehicleType_PoliceCopter {
            get {
                return ResourceManager.GetString("VehicleType_PoliceCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post.
        /// </summary>
        internal static string VehicleType_Post {
            get {
                return ResourceManager.GetString("VehicleType_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private plane.
        /// </summary>
        internal static string VehicleType_PrivatePlane {
            get {
                return ResourceManager.GetString("VehicleType_PrivatePlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rocket.
        /// </summary>
        internal static string VehicleType_Rocket {
            get {
                return ResourceManager.GetString("VehicleType_Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snow truck.
        /// </summary>
        internal static string VehicleType_SnowTruck {
            get {
                return ResourceManager.GetString("VehicleType_SnowTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taxi.
        /// </summary>
        internal static string VehicleType_Taxi {
            get {
                return ResourceManager.GetString("VehicleType_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tram.
        /// </summary>
        internal static string VehicleType_Tram {
            get {
                return ResourceManager.GetString("VehicleType_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trolleybus.
        /// </summary>
        internal static string VehicleType_Trolleybus {
            get {
                return ResourceManager.GetString("VehicleType_Trolleybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water truck.
        /// </summary>
        internal static string VehicleType_WaterTruck {
            get {
                return ResourceManager.GetString("VehicleType_WaterTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Air {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Cargo {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copters.
        /// </summary>
        internal static string VehicleTypeGroup_Copters {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Copters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Default {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Passenger {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger air vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerAir {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger rail vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerRail {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger road vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerRoad {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger water vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerWater {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Planes.
        /// </summary>
        internal static string VehicleTypeGroup_Planes {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rail vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Rail {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Road vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Road {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Service {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ships.
        /// </summary>
        internal static string VehicleTypeGroup_Ships {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Ships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trains.
        /// </summary>
        internal static string VehicleTypeGroup_Trains {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trucks.
        /// </summary>
        internal static string VehicleTypeGroup_Trucks {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Water {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Water", resourceCulture);
            }
        }
    }
}
