//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingSpawnPoints {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildingSpawnPoints.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change and add vehicles spawn points.
        /// </summary>
        internal static string Mod_Description {
            get {
                return ResourceManager.GetString("Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Resolved conflict with More Effective Transfer Manager mod.
        ///- Added Dutch, French and Portuguese translations..
        /// </summary>
        internal static string Mod_WhatsNewMessage1_0_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added Italian translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage1_0_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added depot (bus, trolley, tram, train, copter, blimp, etc). Now posible make custom depots.
        ///- Added transport station, but it will work only like depot. Stop position set by transport line.
        ///- Added cargo stations (train, plane, ship). Truck points not implimented yet.
        ///- Added fishing harbor(fishing boat), shelter(evacuation bus), tour building(tour bus, balloon).
        ///- Added copters (police, ambulance, fire, disaster, passenger).
        ///- Added point height.
        ///- Fixed police car, fire truck, park maintenance an [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Mod_WhatsNewMessage1_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added a warning if the point is too far from the road. The point should be no further than 32 meters from the closer road, otherwise pathfinder will not be able to find path for vehicle. That vehicle types will red.
        ///- Added highlighting that show closer road to point. Hover vehicle type to show it.
        ///- The zero height value is now equal to the height of the terrain under the point, so it fixed points on hills or above the water.
        ///- Added mod button to UnifiedUI.
        ///- Added warning about missing libraries fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Mod_WhatsNewMessage1_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added Korean translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage1_2_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - Added Hungarian translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage1_2_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add all types of vehicles.
        /// </summary>
        internal static string Panel_AddAllVehicle {
            get {
                return ResourceManager.GetString("Panel_AddAllVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add point.
        /// </summary>
        internal static string Panel_AddPoint {
            get {
                return ResourceManager.GetString("Panel_AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add vehicle type.
        /// </summary>
        internal static string Panel_AddVehicle {
            get {
                return ResourceManager.GetString("Panel_AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add vehicle type group.
        /// </summary>
        internal static string Panel_AddVehicleGroup {
            get {
                return ResourceManager.GetString("Panel_AddVehicleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}°.
        /// </summary>
        internal static string Panel_AngleFormat {
            get {
                return ResourceManager.GetString("Panel_AngleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to all buildings of this type.
        /// </summary>
        internal static string Panel_ApplyToAll {
            get {
                return ResourceManager.GetString("Panel_ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string Panel_Copy {
            get {
                return ResourceManager.GetString("Panel_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate point.
        /// </summary>
        internal static string Panel_DuplicatePoint {
            get {
                return ResourceManager.GetString("Panel_DuplicatePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No point in this building contains these types of vehicles:.
        /// </summary>
        internal static string Panel_NoPointWarning {
            get {
                return ResourceManager.GetString("Panel_NoPointWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на They will spawn in default position..
        /// </summary>
        internal static string Panel_NoPointWarningContinue {
            get {
                return ResourceManager.GetString("Panel_NoPointWarningContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        internal static string Panel_Paste {
            get {
                return ResourceManager.GetString("Panel_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}m.
        /// </summary>
        internal static string Panel_PositionFormat {
            get {
                return ResourceManager.GetString("Panel_PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to default.
        /// </summary>
        internal static string Panel_ResetToDefault {
            get {
                return ResourceManager.GetString("Panel_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building #{0}.
        /// </summary>
        internal static string Panel_Title {
            get {
                return ResourceManager.GetString("Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This point placed too far from road for some type of vehicles, move it closer, otherwise it will not work.
        /// </summary>
        internal static string Panel_TooFarPoint {
            get {
                return ResourceManager.GetString("Panel_TooFarPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle.
        /// </summary>
        internal static string PointType_Middle {
            get {
                return ResourceManager.GetString("PointType_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spawn.
        /// </summary>
        internal static string PointType_Spawn {
            get {
                return ResourceManager.GetString("PointType_Spawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspawn.
        /// </summary>
        internal static string PointType_Unspawn {
            get {
                return ResourceManager.GetString("PointType_Unspawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Property_PointType {
            get {
                return ResourceManager.GetString("Property_PointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        internal static string Property_Position {
            get {
                return ResourceManager.GetString("Property_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to all buildings of type.
        /// </summary>
        internal static string Tool_ApplyToAllCaption {
            get {
                return ResourceManager.GetString("Tool_ApplyToAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want apply this setting to all buildings of this type?.
        /// </summary>
        internal static string Tool_ApplyToAllMessage {
            get {
                return ResourceManager.GetString("Tool_ApplyToAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Building #{0}.
        /// </summary>
        internal static string Tool_InfoHoverBuilding {
            get {
                return ResourceManager.GetString("Tool_InfoHoverBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select building.
        /// </summary>
        internal static string Tool_InfoSelectBuilding {
            get {
                return ResourceManager.GetString("Tool_InfoSelectBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string VehicleType_All {
            get {
                return ResourceManager.GetString("VehicleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambulance.
        /// </summary>
        internal static string VehicleType_Ambulance {
            get {
                return ResourceManager.GetString("VehicleType_Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ambulance copter.
        /// </summary>
        internal static string VehicleType_AmbulanceCopter {
            get {
                return ResourceManager.GetString("VehicleType_AmbulanceCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balloon.
        /// </summary>
        internal static string VehicleType_Balloon {
            get {
                return ResourceManager.GetString("VehicleType_Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bicycle.
        /// </summary>
        internal static string VehicleType_Bicycle {
            get {
                return ResourceManager.GetString("VehicleType_Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bus.
        /// </summary>
        internal static string VehicleType_Bus {
            get {
                return ResourceManager.GetString("VehicleType_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cable car.
        /// </summary>
        internal static string VehicleType_CableCar {
            get {
                return ResourceManager.GetString("VehicleType_CableCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo plane.
        /// </summary>
        internal static string VehicleType_CargoPlane {
            get {
                return ResourceManager.GetString("VehicleType_CargoPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo ship.
        /// </summary>
        internal static string VehicleType_CargoShip {
            get {
                return ResourceManager.GetString("VehicleType_CargoShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo train.
        /// </summary>
        internal static string VehicleType_CargoTrain {
            get {
                return ResourceManager.GetString("VehicleType_CargoTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo truck.
        /// </summary>
        internal static string VehicleType_CargoTruck {
            get {
                return ResourceManager.GetString("VehicleType_CargoTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disaster response copter.
        /// </summary>
        internal static string VehicleType_DisasterCopter {
            get {
                return ResourceManager.GetString("VehicleType_DisasterCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disaster response.
        /// </summary>
        internal static string VehicleType_DisasterResponse {
            get {
                return ResourceManager.GetString("VehicleType_DisasterResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fire copter.
        /// </summary>
        internal static string VehicleType_FireCopter {
            get {
                return ResourceManager.GetString("VehicleType_FireCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fire truck.
        /// </summary>
        internal static string VehicleType_FireTruck {
            get {
                return ResourceManager.GetString("VehicleType_FireTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fishing boat.
        /// </summary>
        internal static string VehicleType_FishingBoat {
            get {
                return ResourceManager.GetString("VehicleType_FishingBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Garbage truck.
        /// </summary>
        internal static string VehicleType_GarbageTruck {
            get {
                return ResourceManager.GetString("VehicleType_GarbageTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hearse.
        /// </summary>
        internal static string VehicleType_Hearse {
            get {
                return ResourceManager.GetString("VehicleType_Hearse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metro.
        /// </summary>
        internal static string VehicleType_MetroTrain {
            get {
                return ResourceManager.GetString("VehicleType_MetroTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monorail.
        /// </summary>
        internal static string VehicleType_Monorail {
            get {
                return ResourceManager.GetString("VehicleType_Monorail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Park maintenance.
        /// </summary>
        internal static string VehicleType_ParkMaintenanceTruck {
            get {
                return ResourceManager.GetString("VehicleType_ParkMaintenanceTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger blimp.
        /// </summary>
        internal static string VehicleType_PassengerBlimp {
            get {
                return ResourceManager.GetString("VehicleType_PassengerBlimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger copter.
        /// </summary>
        internal static string VehicleType_PassengerCopter {
            get {
                return ResourceManager.GetString("VehicleType_PassengerCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger ferry.
        /// </summary>
        internal static string VehicleType_PassengerFerry {
            get {
                return ResourceManager.GetString("VehicleType_PassengerFerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger plane.
        /// </summary>
        internal static string VehicleType_PassengerPlane {
            get {
                return ResourceManager.GetString("VehicleType_PassengerPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger ship.
        /// </summary>
        internal static string VehicleType_PassengerShip {
            get {
                return ResourceManager.GetString("VehicleType_PassengerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger train.
        /// </summary>
        internal static string VehicleType_PassengerTrain {
            get {
                return ResourceManager.GetString("VehicleType_PassengerTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Police.
        /// </summary>
        internal static string VehicleType_Police {
            get {
                return ResourceManager.GetString("VehicleType_Police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Police copter.
        /// </summary>
        internal static string VehicleType_PoliceCopter {
            get {
                return ResourceManager.GetString("VehicleType_PoliceCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post.
        /// </summary>
        internal static string VehicleType_PostTruck {
            get {
                return ResourceManager.GetString("VehicleType_PostTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private plane.
        /// </summary>
        internal static string VehicleType_PrivatePlane {
            get {
                return ResourceManager.GetString("VehicleType_PrivatePlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Road maintenance.
        /// </summary>
        internal static string VehicleType_RoadMaintenanceTruck {
            get {
                return ResourceManager.GetString("VehicleType_RoadMaintenanceTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rocket.
        /// </summary>
        internal static string VehicleType_Rocket {
            get {
                return ResourceManager.GetString("VehicleType_Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snowplow.
        /// </summary>
        internal static string VehicleType_SnowTruck {
            get {
                return ResourceManager.GetString("VehicleType_SnowTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taxi.
        /// </summary>
        internal static string VehicleType_Taxi {
            get {
                return ResourceManager.GetString("VehicleType_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tram.
        /// </summary>
        internal static string VehicleType_Tram {
            get {
                return ResourceManager.GetString("VehicleType_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trolleybus.
        /// </summary>
        internal static string VehicleType_Trolleybus {
            get {
                return ResourceManager.GetString("VehicleType_Trolleybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacuum truck.
        /// </summary>
        internal static string VehicleType_VacuumTruck {
            get {
                return ResourceManager.GetString("VehicleType_VacuumTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Air {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cargo vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Cargo {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copters.
        /// </summary>
        internal static string VehicleTypeGroup_Copters {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Copters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Default {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Passenger {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger air vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerAir {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger rail vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerRail {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger road vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerRoad {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger water vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_PassengerWater {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_PassengerWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Planes.
        /// </summary>
        internal static string VehicleTypeGroup_Planes {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rail vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Rail {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Road vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Road {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Service {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ships.
        /// </summary>
        internal static string VehicleTypeGroup_Ships {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Ships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trains.
        /// </summary>
        internal static string VehicleTypeGroup_Trains {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trucks.
        /// </summary>
        internal static string VehicleTypeGroup_Trucks {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water vehicles.
        /// </summary>
        internal static string VehicleTypeGroup_Water {
            get {
                return ResourceManager.GetString("VehicleTypeGroup_Water", resourceCulture);
            }
        }
    }
}
